version: '3.3'

services:
  worker:
    image: collector_worker:3.8.5
    build:
      context: .
      dockerfile: Worker
    env_file:
      - ./image_collector/ENV_FILE
    volumes:
      - ./image_collector:/app/image_collector
      - ./image_collector:/app
    depends_on:
      - broker
    restart: always
    command: bash -c "mkdir -p pictures/big pictures/medium pictures/small pictures/tiny && chmod -R 777 pictures && celery -A image_collector worker --loglevel=info --autoscale=3,1"

  broker:
    image: rabbitmq:3.6.6-management
    hostname: broker
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5673:5672"
      - "15673:15672"
  web:
    image: collector_worker:3.8.5
    volumes:
      - ./image_collector:/app/image_collector
      - ./templates:/app/templates
      - ./static:/app/static
      - ./flask_app.py:/app/flask_app.py
    command: bash -c "python flask_app.py"
    restart: always
    env_file:
      - ./image_collector/ENV_FILE
    depends_on:
      - worker
    ports:
      - "5000:5000"
