version: '3.3'

services:
  worker:
    build:
      context: .
      dockerfile: Worker
    image: collector_worker:3.8.5
    environment:
      - HOSTNAME=broker
      - PORT=5672
      - DB_ACCES_NAME=postgres_db
    env_file:
      - ./image_collector/ENV_FILE
    volumes:
      - ./image_collector:/app/image_collector
      - ./image_collector:/app
    depends_on:
      - broker
    restart: always
    command: bash -c "mkdir -p pictures && chmod -R 777 pictures && celery -A image_collector worker --loglevel=info --autoscale=5,1"

  broker:
    image: rabbitmq:3.6.6-management
    hostname: broker
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5673:5672"
      - "15673:15672"
